function data()
return {
	en = {
		["name"] = "Road and track construction kit",
		["description"] = "Road and track construction kit. You have various setting options. It is very extensive. I am sure that you will enjoy this tool very much.",
	},

	de = {
		["name"] = "Baukasten Strasse und Schienen",
		["description"] = "Strassen- und Schienenbaukasten. Sie haben verschiedene Einstellungsmöglichkeiten. Es ist sehr umfangreich. Ich bin sicher, dass Sie dieses Tool sehr geniessen werden.",

		["Street type"] = "Strassentyp",
		["Street left"] = "Strasse links",
		["Street right"] = "Strasse rechts",
		["Track"] = "Gleis",
		["Bridge type"] = "Brückentyp",
		["Height of bridge"] = "Höhe der Brücke",
		["Height of embankment"] = "Höhe des Dammes",
		["Height of tunnel"] = "Höhe des Tunnels",
		["Number of streets left"] = "Anzahl Strassen links",
		["Number of streets right"] = "Anzahl Strassen rechts",
		["Number of tracks"] = "Anzahl Gleise",
		["Street to street, center distance left"] = "Strasse zu Strasse, Mittenabstand links",
		["Street to street, center distance right"] = "Strasse zu Strasse, Mittenabstand rechts",
		["Track to track, center distance"] = "Gleis zu Gleis, Mittenabstand",
		["Street to track, center distance left"] = "Strasse zu Gleis, Mittenabstand links",
		["Street to track, center distance right"] = "Strasse zu Gleis, Mittenabstand rechts",
		["Length left street"] = "Länge linke Strasse",
		["Length right street"] = "Länge rechte Strasse",
		["Length track"] = "Länge Gleis",
		["Street surface"] = "Strassendecke",
		["Bridge"] = "Brücke",
		["Embankment"] = "Damm",
		["Cement"] = "Zement",
		["Iron"] = "Eisen",
		["Suspension"] = "Hängebrücke",
		["Cable"] = "Kabel",
		["Stone"] = "Stein",
		["Invisible"] = "Unsichtbar",
		["PStone"] = "Stein ohne",
		["PIron"] = "Eisen ohne",
		["PCement"] = "Zement ohne",
		["Track Type"] = "Gleistyp",
		["Catenary"] = "Oberleitung",
		["SS"] = "KS",
		["S1S"] = "K1S",
		["MS"] = "MS",
		["M1S"] = "M1S",
		["LS"] = "GS",
		["L1S"] = "G1S",
		["SC"]= "KL",
		["S1C"] = "K1L",
		["MC"] = "ML",
		["M1C"] = "M1L",
		["LC"] = "GL",
		["L1C"] = "G1L",
	},
}
end